title = 'config'
[url]
BASE_URL = "https://hdu.huitu.zhishulib.com"
LOGIN_URL = "https://hdu.huitu.zhishulib.com/User/Index/login"
SEAT_CHECK_STATE_URL = "https://hdu.huitu.zhishulib.com/Seat/QRCode/checkState"
CATEGORY_LIST_URL = "https://hdu.huitu.zhishulib.com/Space/Category/list"
SEARCH_SEATS_URL = "https://hdu.huitu.zhishulib.com/Seat/Index/searchSeats"
RESERVE_SEAT_URL = "https://hdu.huitu.zhishulib.com/Seat/Index/bookSeats"

[init_headers]
Accept-Encoding = "gzip, deflate, br, zstd"
Accept-Language = "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7"
Connection = "keep-alive"
Host = "hdu.huitu.zhishulib.com"
Origin = "https://hdu.huitu.zhishulib.com"
Referer = "https://hdu.huitu.zhishulib.com/"
Sec-Fetch-Dest = "empty"
Sec-Fetch-Mode = "cors"
Sec-Fetch-Site = "same-origin"
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Accept = "application/json, text/plain, */*"
Content-type = "application/x-www-form-urlencoded;charset=UTF-8"
Sec-ch-ua = ""
Sec-ch-ua-mobile = "?1"
Sec-ch-ua-platform = ""

[room_name_dict]
1000 = "自习室"
1524 = "自习室"
1558 = "自习室"
1525 = "自习室"
1543 = "自习室"
1547 = "生活区"
1548 = "生活区"
1407 = "阅览室"
1408 = "阅览室"
1409 = "阅览室"
1410 = "阅览室"
1411 = "阅览室"
1412 = "阅览室"
1405 = "阅览室"
1404 = "阅览室"
1403 = "阅览室"

[floor_name_dict]
1000 = "二楼东学习空间"
1524 = "二楼西学习空间"
1558 = "四楼学习空间"
1525 = "三楼大厅"
1547 = "求新书院"
1548 = "守正书院"
1407 = "研修中心（六楼）"
1408 = "自然科学第二书库（七楼）"
1409 = "社会科学第二数据（八楼）"
1410 = "文学艺术书库（九楼）"
1411 = "综合第二书库（十楼）"
1412 = "综合第一书库（十一楼）"
1543 = "十二楼学习空间"
1405 = "社会科学书库（三楼北）"
1404 = "社会科学书库（三楼西）"
1403 = "自然科学书库（三楼东）"


[state_dict]
MSG_TIME_OUT_OF_RANGE = "超出可预约座位时间范围"
MSG_DUPLICATE = "已有预约，请勿重复预约！"
MSG_SEAT_UNAVAILABLE = "选择的座位无法预约，可能座位不可用或已经被其他人锁定或占用，请换一个再试"
MSG_INVALID_REQUEST = "非法请求"
MSG_NO_RESPONSE = "无响应"
